name = "NonlinearPDE"
uuid = "36a2d11c-6968-468e-9947-2efb1d74d80d"
authors = ["Yifan Chen <yifanc96@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
